# Site settings
title: Theo's notes
description: "Notes on a variety of topics"
url: "http://www.tpb1908.github.io"
author:
  name: "Theo Pearson-Bray"
  email: "theopearsonbray@gmail.com"

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

sass:
    sass_dir: _sass
    style: compressed

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-seo-tag

jekyll-minifier:
  exclude: 'atom.xml'

# Custom variables
version: "2.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
